#服务端口
server:
  port: 8004

spring:
  #应用名称
  application:
    name: search
  # 格式化日期
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#elasticsearch nodes 节点
elasticsearch:
  nodes: 192.168.31.1:9200  #,192.168.1.X2:9200,192.168.1.X3:9200

#注册中心地址[多个配置中心，中间用逗号分开]
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/ # ,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true

#远程调用配置
feign:
  hystrix:
    enabled: true

#ribbon 超时时间配置
ribbon:
  ReadTimeout: 300000

#熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#打印日志配置
logging:
  level:
    com.mowa.dao: debug
