server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.31.200
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: mowa666
  clientSecret: mowa666
  cookieDomain: localhost
  cookieMaxAge: -1

encrypt:
  key-store:
    location: classpath:/mowa666.jks # 证书路径
    secret: mowa666                  # 密钥
    alias: mowa666                   # 证书的别名
    password: mowa666                # 证书密码

logging:
  level:
    com: debug