#服务端口
server:
  port: 9000

spring:
  #应用名称
  application:
    name: mowa-gateway-web

#注册中心地址[多个配置中心，中间用逗号分开]
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/ # ,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true

#远程调用配置
feign:
  hystrix:
    enabled: true
